export const CREATE_MAIL = "CREATE_MAIL";
export const UPDATE_MAIL = "UPDATE_MAIL";
export const DELETE_MAIL = "DELETE_MAILL";
export const RETRIEVE_MAILS = "RETRIEVE_MAILS";
export const DELETE_ALL_MAILS = "DELETE_ALL_MAILS";